958: Implementing simple idempotency mechanism for payment submission
SecureApiGateway/secure-api-gateway-ob-uk-rs pull request #221
Opened 2023-07-31 15:14 UTC by dbadham-fr

- Fixing bug in PaymentSubmissionRepository which meant that certain payments do not find any records because they query the wrong field
  - Created Extension repository definitions and implementations for each payment type which use MongoTemplate directly to do the querying
- Creating IdempotentPaymentService which is used to find any existing payments with matching idempotency data
- Idempotency checks are shifted earlier in the controller impl in order to avoid validation failures

As noted in the code, this approach to idempotency is simplified. It is not guaranteed to work when there are concurrent requests, due to doing a check to see if a payment exists without any locking. This approach is deemed good enough for a test facility, as it allows developers to test the contract in a sequential fashion.

https://github.com/SecureApiGateway/SecureApiGateway/issues/958

2023-08-01 15:15 UTC, dbadham-fr commented
This PR is a work in progress.

@BohoCode @jorgesanchezperez please can you review the approach and let me know any feedback.

I've migrated Domestic Payments and VRP to use the new idempotency service. All other controllers need to be updated, and test coverage adding.

2023-08-01 15:29 UTC, jorgesanchezperez requested changes
Small fix requested, typo

2023-08-01 15:29 UTC, jorgesanchezperez commented on secure-api-gateway-ob-uk-rs-resource-store/secure-api-gateway-ob-uk-rs-resource-store-repo/src/main/java/com/forgerock/sapi/gateway/rs/resource/store/repo/mongo/payments/DomesticVrpPaymentSubmissionRepository.java
> +     * Find if a payment already exists with the same idempontencyKey within the expieration window.
Typo `expieration`

2023-08-04 14:23 UTC, jorgesanchezperez approved these changes

2023-08-04 14:26 UTC, merged